[versions]
kotlinx-coroutines = "1.9.0-RC"
kotlin-stdlib = "2.0.0"

[libraries]
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines"}
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version = "kotlin-stdlib" }

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version = "1.9.22" }
