package euler.problems

// How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

object Problem29 {
    fun setOfPowers(aRange: IntRange, bRange: IntRange)= aRange.flatMap { a->
        bRange.map { b ->
            BigInteger(a).pow(b)
        }
    }
}